// The ozone climatology of js/physics/ozone.module.js: the ozone column above
// each pressure of a fixed grid for the five AFGL atmospheres (Anderson et al.
// 1986, AFGL-TR-86-0110; the layer means of data/radiationBenchmark.json, from
// libRadtran's afgl*.dat), written to js/physics/ozoneTable.module.js:
//   node scripts/ozoneTable.mjs
import { writeFileSync } from 'node:fs';
import { BENCHMARK, MOLAR } from './standardAtmospheres.mjs';
import { OZONE_CM_ATM } from '../js/physics/shortwaveGases.module.js';
import { GRAVITY } from '../js/dynamics/sigmaCore.module.js';

const PROFILES = ['AFGL_TR', 'AFGL_MS', 'AFGL_MW', 'AFGL_SS', 'AFGL_SW'];
const LOWEST = 0.1, HIGHEST = 110000, POINTS = 81;
const pressures = Array.from({ length: POINTS }, (_, j) => LOWEST * (HIGHEST / LOWEST) ** (j / (POINTS - 1)));

function columnAbove(layers, p) {
  let column = 0;
  for (const l of layers) {
    const top = l.pTop, bottom = l === layers[0] ? Infinity : l.pBottom;
    if (p <= top) continue;
    column += l.o3 * MOLAR.o3 / MOLAR.air * (Math.min(p, bottom) - top) / GRAVITY / OZONE_CM_ATM;
  }
  return column;
}

const rows = PROFILES.map((a) => {
  const layers = BENCHMARK.atmospheres[a].layers;
  return pressures.map((p) => +columnAbove(layers, p).toPrecision(6));
});
for (const [j, a] of PROFILES.entries()) console.log(`${a.padEnd(8)} column above 1013.25 hPa ${(1000 * columnAbove(BENCHMARK.atmospheres[a].layers, 101325)).toFixed(1)} DU, above 10 hPa ${(1000 * rows[j][pressures.findIndex((p) => p >= 1000)]).toFixed(1)} DU`);
writeFileSync(new URL('../js/physics/ozoneTable.module.js', import.meta.url), `// Generated by scripts/ozoneTable.mjs: the ozone column (cm-atm) above each pressure of OZONE_GRID for the AFGL
// tropical, midlatitude summer and winter, and subarctic summer and winter atmospheres (Anderson et al. 1986).
export const OZONE_GRID = { lowest: ${LOWEST}, highest: ${HIGHEST}, points: ${POINTS} };
export const OZONE_PROFILES = [\n${rows.map((r) => `  [${r.join(', ')}],`).join('\n')}\n];\n`);
